export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const NEW_STUDENT = 'NEW_STUDENT';
export const NEW_STUDENT_PENDING = 'NEW_STUDENT_PENDING';
export const SAVE_STUDENT_FULFILLED = 'SAVE_STUDENT_FULFILLED';
export const SAVE_STUDENT_REJECTED = 'SAVE_STUDENT_REJECTED';
export const FETCH_STUDENT_PENDING = 'FETCH_STUDENT_PENDING';
export const FETCH_STUDENT_FULFILLED = 'FETCH_STUDENT_FULFILLED';
