export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const NEW_STUDENT = 'NEW_STUDENT';
export const NEW_STUDENT_PENDING = 'NEW_STUDENT_PENDING';
export const SAVE_STUDENT_FULFILLED = 'SAVE_STUDENT_FULFILLED';
export const SAVE_STUDENT_REJECTED = 'SAVE_STUDENT_REJECTED';
export const FETCH_STUDENT_PENDING = 'FETCH_STUDENT_PENDING';
export const FETCH_STUDENT_FULFILLED = 'FETCH_STUDENT_FULFILLED';
export const FLASH_MESSAGE = 'FLASH_MESSAGE';


export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT = "LOGIN_FAILURE"
export const USER_BACK = "USER_BACK"
export const ADD_PROFILE = "ADD_PROFILE"
export const REMOVE_PROFILE = "REMOVE_PROFILE"


export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

